INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('PLANO','TX','75023');
INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('FRISCO','TX','75033');
INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('ALLEN','TX','75002');
INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('ADDISON','TX','75001');
INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('KELLER','TX','76244');
INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('DEERFIELD','IL','60015');
INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('DES PLAINES','IL','60016');
INSERT INTO LOCATION (CITY,STATE,ZIPCODE) VALUES('DALLAS','TX','75204');