apiVersion: v1
kind: Namespace
metadata:
  name: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-pod
  namespace: order
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order-server
  template:
    metadata:
      labels:
        name: order-server
    spec:
      containers:
        - name: order-service
          image: ltgo/load-management-service
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "500m"
              memory: "750Mi"
            requests:
              cpu: "200m"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              port: 8082
              path: /manage/health
            initialDelaySeconds: 80
          readinessProbe:
            httpGet:
              path: /manage/health
              port: 8082
            initialDelaySeconds: 80
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order
spec:
  type: ClusterIP
  selector:
    name: order-server
  ports:
    - port: 9191
      targetPort: 8082
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: order
  namespace: order
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: order-service
              servicePort: 9191
            path: /
---